master:
  replicaCount: 1
  heapSize: 512m

data:
  replicaCount: 1

coordinating:
  replicaCount: 1

ingest:
  replicaCount: 1

volumePermissions:
  enabled: true

persistence:
  enabled: true
  storageClass: gp2-csi
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

