volumePermissions:
  enabled: true

persistence:
  enabled: true
  storageClass: gp2-csi
  size: 2Gi

coordinating:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

data:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

ingest:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

master:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

