apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    repoURL: https://github.com/Oh-jongmin/ojm
    targetRevision: main
    path: argocd/fluentd
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

