apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  source:
    chart: fluentd
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.5.3
    helm:
      valueFiles:
        - ../fluentd/values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

