apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Oh-jongmin/ojm
    targetRevision: main
    path: argocd/path
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
