apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: 12.1.3
    helm:
      parameters:
        - name: elasticsearch.hosts[0]
          value: http://elasticsearch-master:9200
        - name: elasticsearch.protocol
          value: http
        - name: elasticsearch.port
          value: "9200"
        - name: elasticsearch.ssl.verificationMode
          value: none
        - name: ingress.enabled
          value: "true"
        - name: ingress.hostname
          value: kibana.greenbespinglobal.store
        - name: ingress.ingressClassName
          value: alb
        - name: ingress.annotations."alb\.ingress\.kubernetes\.io/scheme"
          value: internet-facing
        - name: ingress.annotations."alb\.ingress\.kubernetes\.io/target-type"
          value: ip
        - name: ingress.annotations."alb\.ingress\.kubernetes\.io/backend-protocol"
          value: HTTP
        - name: ingress.annotations."alb\.ingress\.kubernetes\.io/certificate-arn"
          value: arn:aws:acm:ap-northeast-2:560971842042:certificate/080d3188-5459-4d21-884e-d9428500d5f5
        - name: persistence.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

