apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: 12.1.3
    helm:
      parameters:
        - name: elasticsearch.hosts[0]
          value: elasticsearch.logging.svc.cluster.local
        - name: elasticsearch.protocol
          value: http
        - name: elasticsearch.port
          value: "9200"
        - name: elasticsearch.ssl.verificationMode
          value: none
        - name: persistence.enabled
          value: "false"
        - name: resources.requests.cpu
          value: "100m"
        - name: resources.requests.memory
          value: "256Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

