apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/kibana
    repoURL: https://github.com/Oh-jongmin/ojm
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

