apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/petclinic-infra.git
    targetRevision: main
    path: monitoring
    kustomize:
      namePrefix: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

