rbac:
  create: true

tolerations:
  - operator: "Exists"

fluentdConfig:
  output:
    elasticsearch:
      host: elasticsearch.logging.svc.cluster.local
      port: 9200
      logstash_prefix: fluentd

image:
  tag: v1.14.2-debian-elasticsearch7-1.0

