apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:b8aa9ae4bb889492aeb14656fd61ceee6c4f3482
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          volumeMounts:
            - name: app-config-volume
              mountPath: /app/config/data-access.properties
              subPath: data-access.properties
            - name: app-secret-volume
              mountPath: /app/config/secret.properties
              subPath: secret.properties
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
            items:
              - key: data-access.properties
                path: data-access.properties
        - name: app-secret-volume
          secret:
            secretName: db-secret
            items:
              - key: secret.properties
                path: secret.properties
