apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: app
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://pnp-rds.ckvfjfutrkfo.ap-northeast-2.rds.amazonaws.com:3306/petclinic
  SPRING_DATASOURCE_USERNAME: pnp
  SPRING_DATASOURCE_PASSWORD: pnp12345
