apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: app
type: Opaque
stringData:
  secret.properties: |
    jdbc.username=pnp
    jdbc.password=pnp12345
    jdbc.url=jdbc:mysql://pnp-rds.ckvfjfutrkfo.ap-northeast-2.rds.amazonaws.com/petclinic?useUnicode=true
