autoDiscovery:
  clusterName: pnp-cluster

awsRegion: ap-northeast-2

rbac:
  serviceAccount:
    create: true
    name: cluster-autoscaler

extraArgs:
  skip-nodes-with-system-pods: false
  skip-nodes-with-local-storage: false
  balance-similar-node-groups: true
  expander: least-waste

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"
    operator: "Exists"

fullnameOverride: cluster-autoscaler

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

