name: CI/CD for Petclinic

on:
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | \
        docker login --username AWS --password-stdin 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com
    - name: Build & Push Web image
      run: |
        docker build -t pnp-ecr docker/web/
        docker tag pnp-ecr 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:web-final
        docker push 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:web-final

    - name: Build & Push App image
      run: |
        docker build -t pnp-ecr docker/app/
        docker tag pnp-ecr 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:app-final
        docker push 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/pnp-ecr:app-final
