name: Build and Push Petclinic to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'petclinic_btc/**'
      - '.github/workflows/petclinic.yaml'

env:


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Maven 3.6.3
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.6.3'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get Git commit SHA
        id: vars
        run: echo "GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$GIT_SHA .
          docker tag ${{ secrets.ECR_REPOSITORY }}:$GIT_SHA ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:$GIT_SHA
          docker push ${{ secrets.ECR_REPOSITORY }}:latest 
