replicaCount: 1

elasticsearch:
  hosts:
    - https://elasticsearch.logging.svc.cluster.local:9200
  protocol: https
  port: 9200
  ssl:
    verificationMode: none

service:
  enabled: true
  type: ClusterIP
  port: 5601

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

