replicaCount: 1

elasticsearch:
  hosts:
    - http://elasticsearch-master:9200
  protocol: http
  port: 9200
  ssl:
    verificationMode: none

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: true
  ingressClassName: alb
  hostname: kibana.greenbespinglobal.store
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:560971842042:certificate/080d3188-5459-4d21-884e-d9428500d5f5

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
